# Config file for my blog

# General config
timezone: "Asia/Singapore"

# Theme config
theme: jekyll-theme-minimal

# General info
title: HelsinkiTart's Blog
description: NetDevOps

# Navigation bar links
navbar-links:
  About Me: Blabla about me
